export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const assignmentConstants = {
  ASSIGNMENT_LIST_REQUEST: "ASSIGNMENT_LIST_REQUEST",
  ASSIGNMENT_LIST_SUCCESS: "ASSIGNMENT_LIST_SUCCESS",
  ASSIGNMENT_LIST_FAIL: "ASSIGNMENT_LIST_FAIL",
  ASSIGNMENT_DETAILS_REQUEST: "ASSIGNMENT_DETAILS_REQUEST",
  ASSIGNMENT_DETAILS_SUCCESS: "ASSIGNMENT_DETAILS_SUCCESS",
  ASSIGNMENT_DETAILS_FAIL: "ASSIGNMENT_DETAILS_FAIL",
  ASSIGNMENT_SAVE_REQUEST: "ASSIGNMENT_SUBMIT_REQUEST",
  ASSIGNMENT_SAVE_SUCCESS: "ASSIGNMENT_SUBMIT_SUCCESS",
  ASSIGNMENT_SAVE_FAIL: "ASSIGNMENT_SUBMIT_FAIL",
};
